### PR TITLE
Draft version send mail

### PR DESCRIPTION
**Pull request by YuriyTigiev**
Not final 
Doesn't work 
Used deno fmt

### CODE REVIEW

**Review by vicky-gonsalves — COMMENTED** [review]
Looks Good to me!

**Comment by YuriyTigiev** [comment]
I can't continue the development because I'm waiting for the solution to fix issues

```
Check file:///C:/Users/yuriy/source/repos/deno_rest/deps.ts
error: TS2305 [ERROR]: Module '"https://deno.land/x/mongo@v0.20.0/mod.ts"' has no exported member 'Bson'.
export { Bson, MongoClient } from "https://deno.land/x/mongo/mod.ts";
         ~~~~
    at file:///C:/Users/yuriy/source/repos/deno_rest/deps.ts:16:10

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { IRequestBody, sendMail } from "https://deno.land/x/sendgrid/mod.ts";
         ~~~~~~~~~~~~
    at file:///C:/Users/yuriy/source/repos/deno_rest/deps.ts:21:10

Found 2 errors.
```

**Comment by vicky-gonsalves** [comment]
Ok I ll try to open PR to mongo developers tomorrow. Let's see if they approve it.

**Comment by YuriyTigiev** [comment]
> Ok I ll try to open PR to mongo developers tomorrow. Let's see if they approve it.

What do you think about Postgres?  and DenoDB https://deno.land/x/denodb@v1.0.18 ? 

P.S.
Contact me by whatsapp

**Comment by vicky-gonsalves** [comment]
@YuriyTigiev I have resolved mongo issue and sanitized/lint fixed and formatted the code. Could you please pull dev branch into ur repository and see if whole code everything is in place? Please take backup of your repository before pulling dev branch into urs repo.

**Comment by vicky-gonsalves** [comment]
Merged with #19

**Pull request closed without merging**
